[[page]]
name = "Homepage"
icon = "ğŸ "
path = "pages/homepage.py"

[[page]]
name = "Peatland Monitoring"
icon = "ğŸ“Š"
path = "pages/peatland2.py"

[[page]]
name = "Chatbot"
icon = "âš™ï¸"
path = "pages/chatbot2.py"

[[page]]
name = "Footprint Calculator"
icon = "âš™ï¸"
path = "pages/footprint3.py"

[[page]]
name = "Analyzer"
icon = "ğŸ "
path = "pages/nlp2.py"

[[page]]
name = "Business"
icon = "ğŸ“Š"
path = "pages/business.py"

[[page]]
name = "Offset"
icon = "âš™ï¸"
path = "pages/credit6.py"